### ISSUE TITLE
[Suggest] Use Clippy to Always on Top & Automatic animated beetween time

### ISSUE THREAD

**Issue by Am1nCmd** [Cosmo/Clippy#3]
Hello, thank you for creating Clippy,

I have more suggest for better Clippy
1. Use Clippy to always on top in layer
2. Use automatic between time ex : 30s-60s will be automatic animated
3. as an option between number 2 maybe it can be animated just by click, instead of rightclick and animated

thank you

**Comment by Cosmo** [comment]
Thanks for the suggestion @Am1nCmd!
Update is out! :) 
[x] Always on top 🎉
[x] Double click to animate

Rest will follow :)

**Comment by include** [comment]
Hi, just to say "I LOVE THIS" :) many thanks 🙏 

BTW: the timer (automatic animated) does not work.
(I think you didn't merge your development branch to master and released an updated zip :)

**Comment by Cosmo** [comment]
@abhiperry added idle animations to Clippy! 🎉
