### ISSUE TITLE
What is the black paperclip symbol and what am I missing in the process?

### ISSUE THREAD

**Issue by DanJ210** [Cosmo/Clippy#6]
Not sure I understand the instructions. I unzipped and have the clippy looking icon. Double clicking does nothing. Nothing happens. The line below is something I'm not seeing anywhere and I don't know what the black paperclip looking character below means ->  📎 -> never seen this before.

Pick an Agent under 📎 → Agents → …

**Comment by Cosmo** [comment]
Hi @DanJ210, do you see a paperclip in the top of the your menu bar of macOS?

**Comment by DanJ210** [comment]
@Cosmo Oh yes I do. I'm not a Mac user I just have one from work that I don't use. So after I select Agents -> Reload, there's still no agents found. I still have to install an individual agent like, Clippy?

**Comment by Cosmo** [comment]
1. When you run Clippy for the first time, you have to select the paperclip icon in the menubar and click on "show in finder". 
2. A finder window with 3 zip archives should popup.
3. Unzip all 3 archives. 
4. Once you did that, go to the paperclip icon in the menu bar again and select Agents -> Reload.
5. Final step: click on the paperclip again, this time under "Agents" you should see other agents.

That should do the trick. If not, let me know :)

I know it might sound complicated — i'll make it easier in the future ;)

**Comment by DanJ210** [comment]
Yup that helped a lot. Sorry for my newbness. Thank you for the enthusiastic help @Cosmo! Impactful user friendliness!
